FROM debian:bullseye-slim AS rdkit-env

# Install runtime dependencies
RUN apt-get update \
 && apt-get install -yq --no-install-recommends \
    libboost-all-dev \
    libcairo2-dev \
    python3-dev \
    python3-numpy \
    python3-cairo \
    python3-pip \
    python3-rdkit \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

