# Generated by Django 3.0.3 on 2020-04-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='affiliation',
            field=models.CharField(default='', max_length=150, verbose_name='affiliation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='field_of_work',
            field=models.CharField(default='', max_length=150, verbose_name='field of work'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(default='', max_length=150, verbose_name='state'),
            preserve_default=False,
        ),
    ]
