# Generated by Django 3.0.3 on 2020-04-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200409_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='affiliation',
            field=models.CharField(max_length=150, verbose_name='Organization/Company'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='field_of_work',
            field=models.CharField(choices=[('', 'Field of Work'), ('industry', 'Industry'), ('private_consulting', 'Private Consulting'), ('academia', 'Academia/Education'), ('research', 'Research'), ('government', 'Government Agency'), ('nonprofit_org', 'Non-profit Organization'), ('other', 'Other')], default='', max_length=150, verbose_name='Field of Work'),
        ),
    ]
