# Generated by Django 3.0.3 on 2020-08-27 20:33

from django.db import migrations

def forwards_func(apps, schema_editor):
    pass

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0002_microbialhost_init_data'),
    ]

    operations = [
    ]
