# Generated by Django 3.0.3 on 2020-09-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0002_auto_20200924_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blend',
            name='fp_tst',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
