# Generated by Django 3.0.3 on 2020-09-26 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0003_auto_20200924_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemical',
            name='synonyms',
        ),
        migrations.CreateModel(
            name='ChemicalSynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('chem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chem.Chemical')),
            ],
        ),
    ]
