# Generated by Django 3.0.3 on 2020-09-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0005_auto_20200926_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('link', models.URLField(blank=True, default='#', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='bp_exp_srcs',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='cn_exp_srcs',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='dcn_exp_srcs',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='fp_exp_srcs',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='mp_exp_srcs',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='ysi_exp_srcs',
        ),
        migrations.AddField(
            model_name='chemical',
            name='bp_exp_srcs',
            field=models.ManyToManyField(blank=True, null=True, related_name='bp_exp_srcs', to='chem.Source'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='cn_exp_srcs',
            field=models.ManyToManyField(blank=True, null=True, related_name='cn_exp_srcs', to='chem.Source'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='dcn_exp_srcs',
            field=models.ManyToManyField(blank=True, null=True, related_name='dcn_exp_srcs', to='chem.Source'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='fp_exp_srcs',
            field=models.ManyToManyField(blank=True, null=True, related_name='fp_exp_srcs', to='chem.Source'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='mp_exp_srcs',
            field=models.ManyToManyField(blank=True, null=True, related_name='mp_exp_srcs', to='chem.Source'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='ysi_exp_srcs',
            field=models.ManyToManyField(blank=True, null=True, related_name='ysi_exp_srcs', to='chem.Source'),
        ),
    ]
