# Generated by Django 3.0.3 on 2020-09-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0006_auto_20200927_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='bp_exp_srcs',
            field=models.ManyToManyField(blank=True, related_name='bp_exp_srcs', to='chem.Source'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='cn_exp_srcs',
            field=models.ManyToManyField(blank=True, related_name='cn_exp_srcs', to='chem.Source'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='dcn_exp_srcs',
            field=models.ManyToManyField(blank=True, related_name='dcn_exp_srcs', to='chem.Source'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='fp_exp_srcs',
            field=models.ManyToManyField(blank=True, related_name='fp_exp_srcs', to='chem.Source'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='mp_exp_srcs',
            field=models.ManyToManyField(blank=True, related_name='mp_exp_srcs', to='chem.Source'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='ysi_exp_srcs',
            field=models.ManyToManyField(blank=True, related_name='ysi_exp_srcs', to='chem.Source'),
        ),
    ]
