# Generated by Django 3.0.3 on 2020-09-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0007_auto_20200927_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemical',
            old_name='bp_pred_err',
            new_name='bp_pred_perc_err',
        ),
        migrations.RenameField(
            model_name='chemical',
            old_name='dcn_pred_err',
            new_name='dcn_pred_perc_perc_err',
        ),
        migrations.RenameField(
            model_name='chemical',
            old_name='fp_pred_err',
            new_name='fp_pred_perc_err',
        ),
        migrations.RenameField(
            model_name='chemical',
            old_name='mp_pred_err',
            new_name='mp_pred_perc_err',
        ),
        migrations.RenameField(
            model_name='chemical',
            old_name='ysi_pred_err',
            new_name='ysi_pred_perc_err',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='cn_pred_err',
        ),
        migrations.AddField(
            model_name='chemical',
            name='cn_pred_perc_err',
            field=models.FloatField(blank=True, default=21.0, null=True),
        ),
    ]
