# Generated by Django 3.0.3 on 2020-09-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0008_auto_20200928_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemical',
            old_name='dcn_pred_perc_perc_err',
            new_name='dcn_pred_perc_err',
        ),
    ]
