# Generated by Django 3.0.3 on 2020-09-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0011_auto_20200929_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='_struct_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='/Users/tylerhuntington222/ftf-django/media'),
        ),
    ]
