# Generated by Django 3.0.3 on 2020-09-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0016_auto_20200929_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='_struct_img',
            field=models.FilePathField(blank=True, null=True, verbose_name='chem/static/chem/img/structures'),
        ),
    ]
