# Generated by Django 3.0.3 on 2020-09-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0017_auto_20200929_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemicalsubmission',
            name='bp_val',
        ),
        migrations.RemoveField(
            model_name='chemicalsubmission',
            name='cn_val',
        ),
        migrations.RemoveField(
            model_name='chemicalsubmission',
            name='dcn_val',
        ),
        migrations.RemoveField(
            model_name='chemicalsubmission',
            name='fp_val',
        ),
        migrations.RemoveField(
            model_name='chemicalsubmission',
            name='mp_val',
        ),
        migrations.RemoveField(
            model_name='chemicalsubmission',
            name='oth_prop_1_temp',
        ),
        migrations.RemoveField(
            model_name='chemicalsubmission',
            name='oth_prop_3_temp',
        ),
        migrations.RemoveField(
            model_name='chemicalsubmission',
            name='synonyms',
        ),
        migrations.RemoveField(
            model_name='chemicalsubmission',
            name='ysi_val',
        ),
        migrations.AddField(
            model_name='chemicalsubmission',
            name='csv_submission',
            field=models.FileField(blank=True, null=True, upload_to='chem_submissions'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='_struct_img',
            field=models.FilePathField(blank=True, null=True, verbose_name='chem/static/chem/img/structs'),
        ),
        migrations.AlterField(
            model_name='chemicalsubmission',
            name='comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
