# Generated by Django 3.0.3 on 2020-09-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0018_auto_20200930_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blendsubmission',
            old_name='bp_exp_other',
            new_name='bp_exp_oth',
        ),
        migrations.RenameField(
            model_name='blendsubmission',
            old_name='bp_notes_other',
            new_name='bp_notes_0',
        ),
        migrations.RenameField(
            model_name='blendsubmission',
            old_name='bp_src_other',
            new_name='bp_src_oth',
        ),
        migrations.RenameField(
            model_name='blendsubmission',
            old_name='bp_temp_other',
            new_name='bp_temp_oth',
        ),
        migrations.RenameField(
            model_name='blendsubmission',
            old_name='bp_tst_other',
            new_name='bp_tst_oth',
        ),
        migrations.RenameField(
            model_name='blendsubmission',
            old_name='flsh_pt_exp',
            new_name='fp_exp',
        ),
        migrations.RenameField(
            model_name='blendsubmission',
            old_name='flsh_pt_notes',
            new_name='fp_notes',
        ),
        migrations.RenameField(
            model_name='blendsubmission',
            old_name='flsh_pt_src',
            new_name='fp_src',
        ),
        migrations.RenameField(
            model_name='blendsubmission',
            old_name='flsh_pt_tst',
            new_name='fp_tst',
        ),
        migrations.RenameField(
            model_name='blendsubmission',
            old_name='frz_pt_exp',
            new_name='frzp_exp',
        ),
        migrations.RenameField(
            model_name='blendsubmission',
            old_name='frz_pt_notes',
            new_name='frzp_notes',
        ),
        migrations.RenameField(
            model_name='blendsubmission',
            old_name='frz_pt_src',
            new_name='frzp_src',
        ),
        migrations.RenameField(
            model_name='blendsubmission',
            old_name='frz_pt_tst',
            new_name='frzp_tst',
        ),
        migrations.RemoveField(
            model_name='blendsubmission',
            name='oth_prop_1_temp',
        ),
        migrations.AddField(
            model_name='blendsubmission',
            name='bp_notes_oth',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blendsubmission',
            name='bp_src_0',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blendsubmission',
            name='bp_tst_0',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blendsubmission',
            name='csv_submission',
            field=models.FileField(blank=True, null=True, upload_to='blend_csv_submissions'),
        ),
        migrations.AlterField(
            model_name='blendsubmission',
            name='comp_1_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blendsubmission',
            name='comp_1_perc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blendsubmission',
            name='comp_2_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blendsubmission',
            name='comp_2_perc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalsubmission',
            name='csv_submission',
            field=models.FileField(blank=True, null=True, upload_to='chem_csv_submissions'),
        ),
    ]
