# Generated by Django 3.0.3 on 2020-09-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0019_auto_20200930_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendsubmission',
            name='bp_temp_oth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
