# Generated by Django 3.0.3 on 2020-09-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0021_auto_20200930_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalsubmission',
            name='formula',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalsubmission',
            name='smiles',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
