# Generated by Django 3.0.3 on 2020-10-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0022_auto_20200930_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyestimator',
            old_name='serial_mod_fn',
            new_name='train_fit_serial_mod_fn',
        ),
        migrations.AddField(
            model_name='propertyestimator',
            name='full_fit_serial_mod_fn',
            field=models.FilePathField(default='', verbose_name='filestore/ml_models'),
            preserve_default=False,
        ),
    ]
