# Generated by Django 3.0.3 on 2020-10-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0024_auto_20201001_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalsynonym',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
