# Generated by Django 3.0.3 on 2020-10-06 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0026_auto_20201002_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalsynonym',
            name='chem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syns', to='chem.Chemical'),
        ),
    ]
