# Generated by Django 3.0.3 on 2020-10-06 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0027_auto_20201006_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalsynonym',
            name='chem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='chem.Chemical'),
        ),
    ]
