# Generated by Django 3.0.3 on 2021-07-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='bp_pred_err_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='bp_pred_err_up',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='fp_pred_err_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='fp_pred_err_up',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='hoc_pred_err_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='hoc_pred_err_up',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='mp_pred_err_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='mp_pred_err_up',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='ysi_pred_err_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='ysi_pred_err_up',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
