# Generated by Django 3.0.3 on 2021-07-13 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0002_auto_20210713_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='bp_estimator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_estimator', to='chem.PropertyEstimator'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='cn_estimator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cn_estimator', to='chem.PropertyEstimator'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='dcn_estimator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcn_estimator', to='chem.PropertyEstimator'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='fp_estimator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fp_estimator', to='chem.PropertyEstimator'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='mp_estimator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mp_estimator', to='chem.PropertyEstimator'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='ysi_estimator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ysi_estimator', to='chem.PropertyEstimator'),
        ),
    ]
