# Generated by Django 3.0.3 on 2021-07-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0003_auto_20210713_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='hoc_pred',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
