# Generated by Django 3.0.3 on 2021-07-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0004_chemical_hoc_pred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalsubmission',
            name='contrib_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
