# Generated by Django 3.0.3 on 2021-07-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0005_auto_20210715_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalsubmission',
            name='contrib_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
