# Generated by Django 3.0.3 on 2021-07-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0006_auto_20210716_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendsubmission',
            name='contrib_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalsubmission',
            name='contrib_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
